// Data laptop
const laptop = [
  {
    brand: "lenovo",
    type: "thinkpad l490",
    processor: "Intel Core i5 gen 8",
    ram: "8GB",
    storage: "256GB SSD",
    layar: "14 inch",
    kondisi: "Buildup",
    keterangan: "",
    url_img: "img/products/lenovo-thinkpad-l490.png",
    price: 5450000,
    discount: 4150000,
  },
  {
    brand: "acer",
    type: "aspire ES1-132",
    processor: "Intel Celeron 3350U",
    ram: "4GB",
    storage: "128GB SSD",
    layar: "11.5 inch",
    kondisi: "Buildup",
    keterangan: "",
    url_img: "img/products/acer-aspire-es1-132.png",
    price: 3799000,
    discount: 2799000,
  },
  {
    brand: "lenovo",
    type: "thinkpad X1 carbon",
    processor: "Intel Core i5 gen 8",
    ram: "8GB",
    storage: "256GB SSD",
    layar: "14 inch",
    kondisi: "Buildup",
    keterangan: "",
    url_img: "img/products/lenovo-thinkpad-x1-carbon.webp",
    price: 5299000,
    discount: 4999000,
  },
  {
    brand: "advan",
    type: "soulmate",
    processor: "Intel Celeron N4020",
    ram: "4GB",
    storage: "128GB SSD",
    layar: "14 inch",
    kondisi: "Baru",
    keterangan: "",
    url_img: "img/products/advan-soulmate.png",
    price: 4694000,
    discount: 3299000,
  },
  {
    brand: "axioo",
    type: "hype 1",
    processor: "Intel Celeron N4020",
    ram: "4GB",
    storage: "128GB SSD",
    layar: "14 inch",
    kondisi: "Baru",
    keterangan: "",
    url_img: "img/products/axioo-hype-1.avif",
    price: 4799000,
    discount: 3799000,
  },
  {
    brand: "lenovo",
    type: "chromebook 300e",
    processor: "Intel Celeron N4500",
    ram: "4GB",
    storage: "128GB SSD",
    layar: "12.5 inch",
    kondisi: "Buildup",
    keterangan: "tidak ada pen",
    url_img: "img/products/lenovo-chromebook-300e.png",
    price: 3799000,
    discount: 1999000,
  },
  {
    brand: "lenovo",
    type: "chromebook 300e",
    processor: "Intel Pentium Silver N5000",
    ram: "4GB",
    storage: "128GB SSD",
    layar: "11.6 inch",
    kondisi: "Buildup",
    keterangan: "tidak ada pen",
    url_img: "img/products/lenovo-chromebook-300e.png",
    price: 3799000,
    discount: 1999000,
  },
  {
    brand: "lenovo",
    type: "yoga 11e",
    processor: "Intel Core i5 gen 8",
    ram: "8GB",
    storage: "128GB SSD",
    layar: "12.5 inch",
    kondisi: "Buildup",
    keterangan: "",
    url_img: "img/products/lenovo-yoga-11e.png",
    price: 5199000,
    discount: 3999000,
  },
  {
    brand: "hp",
    type: "elitebook 840 G3",
    processor: "Intel Core i5 gen 6",
    ram: "8GB",
    storage: "256GB SSD",
    layar: "14 inch",
    kondisi: "Buildup",
    keterangan: "",
    url_img: "img/products/hp-elitebook-840-g3.webp",
    price: 5000000,
    discount: 3999000,
  },
  {
    brand: "lenovo",
    type: "thinkpad L14",
    processor: "Intel Core i5 gen 10",
    ram: "8GB",
    storage: "256GB SSD",
    layar: "14 inch",
    kondisi: "Buildup",
    keterangan: "",
    url_img: "img/products/lenovo-thinkpad-l14.avif",
    price: 7650000,
    discount: 6399000,
  },
  {
    brand: "lenovo",
    type: "thinkpad L480",
    processor: "Intel Core i5 gen 8",
    ram: "8GB",
    storage: "256GB SSD",
    layar: "14 inch",
    kondisi: "Buildup",
    keterangan: "",
    url_img: "img/products/lenovo-thinkpad-l480.png",
    price: 5300000,
    discount: 4099000,
  },
  {
    brand: "hp",
    type: "probook 640 G2",
    processor: "Intel Core i5 gen 6",
    ram: "8GB",
    storage: "256GB SSD",
    layar: "14 inch",
    kondisi: "Buildup",
    keterangan: "",
    url_img: "img/products/hp-probook-640-g2.png",
    price: 4199000,
    discount: 3500000,
  },
];
